var tableauQuestion = [
    {   question : "بعد از کشته شدن توسط پلیس آیا اجازه دارید دکمه ی E را نگه دارید تا از بیمارستان زنده بشید؟",
        propositionA : "بله",
        propositionB : "خیر",
        propositionC : "در صورت اجازه دادن پلیس میتوانید",
        propositionD : "در صورت نبود دکتر میتوانید",
        reponse : "C"},
	{   question : "در صورتی که بعد از مرگ دکمه ی E را نگه دارید کدام یک از موارد زیر را از دست میدهید؟",
        propositionA : "تمام وسائل و اسلحه ها",
        propositionB : "پول کثیف",
        propositionC : "پول داخل جیب",
        propositionD : "همه موارد",
        reponse : "D"},
	{   question : "کدام یک از گزینه ها شامل بن نمیشود؟",
        propositionA : "خلاف کردن در صورت رایس بیمارستان بودن",
        propositionB : "خلاف کردن در صورت رایس اداره پلیس بودن",
        propositionC : "تیر اندازی، قتل ، و یا درگیری در مناطق ممنوعه",
        propositionD : "کشتن پلیس ها",
        reponse : "D"},
	{   question : "کدام یک از گزینه های زیر جزو مناطق ممنوع نمیباشد؟",
        propositionA : "اداره پلیس",
        propositionB : "بیمارستان",
        propositionC : "لباس فروشی و آرایشگاه",
        propositionD : "هیچکدام",
        reponse : "D"},
	{   question : "چه وقتی پلیس اجازه شلیک دارد؟",
        propositionA : "زمانی که مجرم ببیند",
        propositionB : "زمانی که مجرم به اخطار پلیس توجه نکند",
        propositionC : "زمانی که مجرم از تفنگ استفاده کند",
        propositionD : "هیچ وقت",
        reponse : "C"},
	{   question : "کی دکتر میتواند از تفنگ استفاده کند؟",
        propositionA : "در زمانی که با لباس شخصی باشد",
        propositionB : "وقتی وسط ماموریت باشد و خلافکاری او را تحدید کند",
        propositionC : "وقتی وسط ماموریت باشد وخلافکاری به سمت او شلیک کند",
        propositionD : "هر وقت دلش بخواد",
        reponse : "A"},
	
]
